### ISSUE TITLE
Checksum mismatch error

### ISSUE THREAD

**Issue by bunubbv** [PeterSuh-Q3/tcrp-modules#2]
안녕하세요. SA6400, 7.2.1로 빌드 진행 중 mpt3sas.ko의 체크섬 불일치로 빌드가 중단되는 현상이 확인되었습니다.

최근 해시 변경 커밋이 있었는데 변경된 해시가 반영되지 않은 것으로 보입니다. 확인 부탁드립니다.

감사합니다.

**Comment by bunubbv** [comment]
최근 DSM 업데이트 후 알 수 없는 이유로 부팅에 실패하여 로더를 다시 빌드하던 중 체크섬 불일치가 발생하였고, 이후 로더 빌드용 디스크를 다시 만든 뒤 빌드를 시도하였는데 여전히 체크섬 불일치 에러로 빌드가 중단되는 것을 확인했습니다.

**Comment by bunubbv** [comment]
SA6400이 아닌 다른 모델의 빌드는 정상 동작하는 것을 확인했습니다. 또한, 최근 7.2.1 Update 5 이후 부트 과정에서 Update 0으로 나오는 문제가 있습니다.

**Comment by PeterSuh-Q3** [comment]
최근 모듈 재배포 과정에서 mpt3sas.ko 와  r8125 체크섬이 잘못 기록된 문제가 있었습니다.
https://github.com/PeterSuh-Q3/tcrp-modules/commit/c0d061b3d9bb972a60531282d643126a7d292d6a
방금 조치 마쳤습니다.
다시 사용해 보시기 바랍니다.

FRIEND 커널 콘솔 화면상에서 Update 5 가 Update 0 로 표기되는것은 내부적으로는 이미
ramdisk & kernel 버전 patch 가 마쳐진 상태이지만 이것으로 다시 이미 위에 표기한 smallfixnumber 에 반영하고 있지 못할 뿐입니다. 단순한 표기의 문제입니다.

재부팅을 하시면 Update 5 대신 Update 4 로 나타나실 겁니다.
이 문제를 해결하기 위해서는 Patch 처리 과정을 버전표기보다 앞서처리하도록 해야 하는데, 이렇게 수정하는것은 고민좀 해보겠습니다.

**Comment by PeterSuh-Q3** [comment]
요청하신 2번째 사항도 반영했습니다.
https://github.com/PeterSuh-Q3/tcrpfriend/commit/f9724794bcdca1699844c01d8e38446e787dfa8a
약간의 버그가 있어서 grub.cfg 에 smallfixnumber 수정기능이 동작되고 있지 않던것도 수정했습니다.

그런데, Update 5 가 Update 4 로 기록되는 문제는 시놀로지에서 Update 정보를 내려 받는부분에서 
시놀로지가 정확한 정보를 내려주지 않아서 어쩔수 없이 버전이 5임이도 4로 기록되는 문제는 계속 있습니다.

시놀로지가 이부분은 세세히 신경을 쓰지 않는 문제라서 저도 어떻게 할 수가 없습니다.
어떤 시점에서는 smallfixnumber 딱 맞아서 내려오는데 이번 5 에서부터는 또 틀어지기 시작했네요.

**Comment by bunubbv** [comment]
버전 번호 같은 부분은 사용 상 지장이 없어 괜찮습니다. 빠르게 조치해 주셔서 정말 감사합니다 :)
